# BSD 3-Clause License All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause License

contact:
  email: powen@renci.org
  name: Phil Owen
  x-id: https://github.com/phillipsowen
  x-role: responsible developer
description: 'Allows for the altering of the iRODS K8s supervisor app'
servers:
- description: Default server
  url: https://irods-k8s-settings.apps.renci.org
title: iRODS K8s Settings
